### ISSUE TITLE
Vulnerability of executing arbitrary code and/or compromising Telegram account via MiTM attacks

### ISSUE THREAD

**Issue by c-h3xcode** [GeekTG/Friendly-Telegram#11]
[Malicious commit](https://github.com/GeekTG/Friendly-Telegram/commit/012b51df410d782a7b3fe85d8029477741a31b67)

Disabling HTTPS verification entails the possibility of MiTM attacks and, consequently, module spoofing. This in turn allows to steal a Telegram session, or execute arbitrary code on the machine where GeekTG is running

**Comment by fast-geek** [comment]
@c-h3xcode @D4n13l3k00 возвращаем назад проверку)

**Comment by D4n13l3k00** [comment]
https://github.com/GeekTG/Friendly-Telegram/commit/5bdb65980c99657b3f534680200a37a59e650ecf
