### ISSUE TITLE
dependency on mautrix

### ISSUE THREAD

**Issue by penn5** [GeekTG/Friendly-Telegram#26]
No code from mautrix is used so it's useless

**Comment by crinnyx** [comment]
@penn5 в фаст аплоадере он юзается ок??

**Comment by fast-geek** [comment]
> No code from mautrix is used so it's useless

It's used in fast_uploader.py, that provides faster download and upload speed of files from Telegram servers

**Comment by penn5** [comment]
> > No code from mautrix is used so it's useless
> 
> It's used in fast_uploader.py, that provides faster download and upload speed of files from Telegram servers

Actually it isn't. That file imports from there but never used the imported function

**Comment by fast-geek** [comment]
> 
> > > No code from mautrix is used so it's useless
> > 
> > It's used in fast_uploader.py, that provides faster download and upload speed of files from Telegram servers
> 
> Actually it isn't. That file imports from there but never used the imported function

Maybe, we used code from GitHub Gist, and have not yet cleared it of unnecessary and useless code, but thanks for the advice

**Comment by fast-geek** [comment]
Mautrix was deleted in [https://github.com/GeekTG/Friendly-Telegram/commit/95ab132fdafa6f45267f1d75379b502818871100](Last commit), thx @penn5

**Comment by KOT4N11** [comment]
@fast-geek bruh
