### ISSUE TITLE
files from test/ directory moved to main code directory

### ISSUE THREAD

**Issue by penn5** [GeekTG/Friendly-Telegram#27]
There's no reason to do that, they're mostly useless and just clutter stuff

**Comment by crinnyx** [comment]
@penn5 братан ну ты че, он для фаст аплоадера юзаетсч

**Comment by fast-geek** [comment]
@crinnyx АХАХАХХАХАХС

**Comment by crinnyx** [comment]
@penn5 сори братиш не туда

**Comment by gamedich** [comment]
Чаго

**Comment by penn5** [comment]
> @penn5 братан ну ты че, он для фаст аплоадера юзаетсч

This is totally irrelevant.

**Comment by Fl1yd** [comment]
@crinnyx ВХАХАХАХАХАХА

**Comment by KOT4N11** [comment]
@Fl1yd кринни успокойся пж

**Comment by fast-geek** [comment]
We kept all the necessary files, and deleted the useless ones

**Comment by KOT4N11** [comment]
@fast-geek okay

**Comment by penn5** [comment]
You can delete them all if you want they aren't used except in my CI
