### ISSUE TITLE
Error installing FriendlyTG on Windows 10 PC

### ISSUE THREAD

**Issue by cyb3rm4n** [GeekTG/Friendly-Telegram#59]
Got next logs on Windows 10 PC (21H2) with default PowerShell

PS C:\Users\cyb3r> iex (New-Object Net.WebClient).DownloadString("https://raw.githubusercontent.com/GeekTG/Friendly-Telegram/master/install.ps1")
Downloading Python...
Installing Python...
Locating Git...
iex (New-Object Net.WebClient).DownloadString("https://raw.githubusercontent.com/GeekTG/Friendly-Telegram/master/instal
l.ps1") : Unable to locate Git
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException

**Comment by D4n13l3k00** [comment]
Install git from https://git-scm.com/

**Comment by fast-geek** [comment]
Add GIT to [Windows PATH](https://en.wikipedia.org/wiki/PATH_(variable))

**Comment by cyb3rm4n** [comment]
User path
![изображение](https://user-images.githubusercontent.com/1812907/150593845-63fee9b7-207e-4e8b-99d7-54d35ea8b5c1.png)
Systemwide path
![изображение](https://user-images.githubusercontent.com/1812907/150593721-f93c4d54-bf9a-4d99-b818-4f13508cb6d8.png)

**Comment by D4n13l3k00** [comment]
Try restarting your PC to accept the change of path

**Comment by cyb3rm4n** [comment]
Doesn't helped.

![изображение](https://user-images.githubusercontent.com/1812907/150594948-9ed556ac-0b0f-430e-a083-89c02ca5cbce.png)

**Comment by hikariatama** [comment]
@D4n13l3k00 💻 Установка и запуск:
https://ftg.geektg.ml/
