### ISSUE TITLE
Restart message doesnt do anything when restarted

### ISSUE THREAD

**Issue by smolovk** [GeekTG/Friendly-Telegram#62]
When i do .restart it edits to "Restarting...", but it never changes or deletes

**Comment by hikariatama** [comment]
Please, ensure you are on the latest commit. Execute
`git stash && git pull -f`
in your GeekTG directory, then manually restart userbot to force update

**Comment by fast-geek** [comment]
@smolovk you can tap "Restart" in lavhostbot

**Comment by gamedich** [comment]
@smolovk ор

**Comment by hikariatama** [comment]
> > @smolovk you can tap "Restart" in lavhostbot
> 
> thought it was a bug in gtg

It was until last update https://github.com/GeekTG/Friendly-Telegram/commit/0996c89f16939baceec7e54790e01d4b90073ffa

**Comment by smolovk** [comment]
ok, thanks
